"""delete age column

Revision ID: ec2b4cf567b9
Revises: a0d5c3622bd3
Create Date: 2019-01-11 17:37:15.230924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2b4cf567b9'
down_revision = 'a0d5c3622bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #instead of op.drop_column('user', 'age')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
