"""initial migration

Revision ID: 106aa899322a
Revises: 
Create Date: 2019-01-11 22:55:25.794161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106aa899322a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('itemsdesc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('imgref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['itemid'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('ordered', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('orderdate', sa.DATETIME(), nullable=True),
    sa.Column('paydate', sa.DATETIME(), nullable=True),
    sa.Column('deliverydate', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['itemid'], ['items.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('validfrom', sa.DATETIME(), nullable=True),
    sa.Column('validto', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['itemid'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('orders')
    op.drop_table('itemsdesc')
    op.drop_table('user')
    op.drop_table('items')
    # ### end Alembic commands ###
