"""initial migration

Revision ID: 7b295a4bf54c
Revises: 
Create Date: 2018-12-25 22:24:19.336108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b295a4bf54c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'itemid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'prices', 'items', ['itemid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.alter_column('prices', 'itemid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
